services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: npm serve

  frontend:
    build:
      context: ./frontend
    ports:
      - "9000:9000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run start-dev
